# Generated by Django 5.2 on 2025-04-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftyear', models.IntegerField()),
                ('drawdate', models.CharField(max_length=50)),
                ('birthyear', models.CharField(max_length=50)),
                ('maxcalled', models.IntegerField()),
            ],
            options={
                'db_table': 'draft_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Draftee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('birthyear', models.CharField(max_length=50)),
                ('drawyear', models.IntegerField()),
                ('draftyear', models.IntegerField()),
                ('halfyear', models.CharField(max_length=50)),
                ('draftnumber', models.IntegerField()),
            ],
            options={
                'db_table': 'draft_info',
                'managed': False,
            },
        ),
    ]
